/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.mathoperations;

import org.junit.Test;

import com.bridgelabz.mathoperations.MathOperationsApp;

import static org.junit.Assert.*;

public class MathOperationsAppTest {
}
