/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.mathoperations;

@FunctionalInterface
interface IMathFunction {
	int calculate(int a, int b);
}

public class MathOperationsApp {
	public static void main(String[] args) {
		IMathFunction add = (a,b) -> a+b;
		IMathFunction subtract = (a,b) -> a-b;
		IMathFunction division = (a,b) -> a/b;
		
		System.out.println("Addition is "+add.calculate(3, 4));
		System.out.println("Subtraction is "+subtract.calculate(6, 5));
		System.out.println("Division is "+division.calculate(18, 3));
	}
}
